var classes = [
  {
    quarter: "Fall 2012",
    course: "CSE 8A",
    title: "Introduction to Computer Science: Java I",
    tools: ["Java"],
  },
  {
    quarter: "Winter 2013",
    course: "CSE 8B",
    title: "Introduction to Computer Science: Java II",
    tools: ["Java"],
  },
  {
    quarter: "Spring 2013",
    course: "CSE 12",
    title: "Basic Data Structures and Object-Oriented Design",
    tools: ["Java", "JUnit"],
  },
  {
    quarter: "Spring 2013",
    course: "CSE 15L",
    title: "Software Tools and Techniques Laboratory",
    tools: ["Unix", "Eclipse", "JUnit"],
  },
  {
    quarter: "Spring 2013",
    course: "CSE 20",
    title: "Discrete Mathematics",
    tools: ["Proofs"],
  },
  {
    quarter: "Summer 2013",
    course: "CSE 21",
    title: "Mathematics for Algorithms and Systems",
    tools: ["Enumerative combinatorics"],
  }, 
  {
    quarter: "Fall 2013",
    course: "CSE 30",
    title: "Computer Organization and Systems Programming",
    tools: ["C", "Assembly", "Unix", "SPARC", "Vim", "Git"],
  }, 
  {
    quarter: "Fall 2013",
    course: "CSE 100",
    title: "Advanced Data Structures",
    tools: ["C++", "Git", "GitHub"],
  }, 
  {
    quarter: "Fall 2013",
    course: "CSE 103",
    title: "A Practical Introduction to Probability and Statistics",
    tools: ["Python"],
  }, 
  {
    quarter: "Winter 2014",
    course: "CSE 101",
    title: "Design and Analysis of Algorithms",
    tools: ["Python"],
  },
  {
    quarter: "Winter 2014",
    course: "CSE 105",
    title: "Theory of Computability",
    tools: ["Haskell"],
  },
  {
    quarter: "Winter 2014",
    course: "CSE 132A",
    title: "Database System Principles",
    tools: ["SQL", "sqlite"],
  },
  {
    quarter: "Spring 2014",
    course: "CSE 110",
    title: "Software Engineering",
    tools: ["Java", "JUnit", "Eclipse", "Spring", "Git"],
  },
  {
    quarter: "Spring 2014",
    course: "CSE 130",
    title: "Programming Languages: Principles and Paradigms",
    tools: ["Ocaml", "Scala"],
  },
  {
    quarter: "Spring 2014",
    course:"CSE 140",
    title: "Components and Design Techniques for Digital Systems",
    tools: [],
  },
  {
    quarter: "Spring 2014",
    course:"CSE 140L",
    title: "Digital Systems Laboratory",
    tools: ["Verilog"],
  },
  {
    quarter: "Summer 2014",
    course: "CSE 134B",
    title: "Web Client Languages",
    tools: ["HTML", "XML", "JavaScript", "Firebase"],
  },
  {
    quarter: "Summer 2014",
    course: "CSE 135",
    title: "Server-side Web Applications",
    tools: ["Apache", "PHP", "JavaScript", "MySQL", "HTML", "Bootstrap", "Linux"],
  },
  {
    quarter: "Fall 2014",
    course: "CSE 120",
    title: "Principles of Computer Operating Systems",
    tools: ["C++", "Git"],
  },
  {
    quarter: "Fall 2014",
    course: "CSE 190",
    title: "Beyond Relational Data Models",
    tools: ["MySQL", "XML", "Ruby", "Rails", "JSON"],
  },
];
